### PR TITLE
Azure CI

### PR DESCRIPTION
**Pull request by blakerosenthal**
Test system for rJourney!

These commits are broken down into three main pieces:
  - Large files from rJourney have been moved to the [rJourney_resources](https://github.com/RSGInc/rJourney_resources) repository. This allows for faster download times, and a logical separation of code from model inputs.
  - `rJourney_1_3.pas` has been tweaked so it can be compiled on Mac or Linux architechture. It also now displays a percentage-based progress bar while reading the large households file.
  - `azure-pipelines.yml` provides instructions to the installed Azure Pipelines hook to build and run rJourney on the wrjmdlppw03 server.

The README has been updated to reflect these changes, and the included `rJourney_1_3.exe` executable has also been updated (although the only functional difference is the progress bar code -- happy to rollback to the earlier version if that would be better).

Azure uses a 500-zone household sample in order to run the model in under 30 minutes on the test server. Target outputs have also been provided that are then compared to the results of each test run.

### CODE REVIEW

**Comment by bstabler** [comment]
Looks good.  Any comments @mabcal?

**Comment by mabcal** [comment]
What is the run time with 50 zones?

**Comment by blakerosenthal** [comment]
> What is the run time with 50 zones? 

@mabcal It's almost immediate. 200 zones is about 12 minutes. I haven't tried it with 50 but I'm sure it's under five minutes.

**Review by bstabler — COMMENTED** [review]
looks good

**Pull request closed without merging**
